### PR TITLE
for_production: validate tasks before running them

### PR DESCRIPTION
**Pull request by bertsky**
(validation must run on target=controller, because tools are only installed there – so we should probably rename `pre_process_validate_workflow` to `ocrd_validate_workflow`)

### CODE REVIEW

**Comment by bertsky** [comment]
BTW, we could also use `ocrd validate tasks --overwrite` / `ocrd process --overwrite` to allow incremental jobs (re-entry). Not sure if this is what we want, though.

**Comment by markusweigelt** [comment]
Ok feel free to rename this function in this context. My initial assumption was that we validate it via a second ssh request. It is much better that way.

**Comment by markusweigelt** [comment]
I think we should add a specific issue for this incremental jobs feature to be able to evaluate this at a later time.

**Comment by bertsky** [comment]
Yeah, a second SSH request would work, too. But since we implicitly connect everything conjunctively already (by `set -e`), I think it's better that way. (Once we start restricting jobs on the controller, it would be easier to have everything in a single call.)

**Pull request merged**
