### PR TITLE
refactoring and CLI for presentation

### PR DESCRIPTION
**Pull request by bertsky**
This is a first working version for an interface from METS to METS.

We might still need fiddle with the details (both in interface definition and implementation).

(One of the problems I saw was that ocrd_browser cannot show workspaces which still have remote images in them, see [here](https://github.com/hnesk/browse-ocrd/issues/52).)

### CODE REVIEW

**Comment by bertsky** [comment]
Note: for adaptation on the Kitodo.Production side, you will need the following patch:
```diff
--- _resources/data/scripts/script_ocr.sh	2022-06-30 15:36:12.000000000 +0200
+++ _resources/data/scripts/script_ocr.sh	2022-09-27 12:23:11.495580732 +0200
@@ -16,11 +16,12 @@
   exit 3
 fi
 
-COMMAND="for_production.sh $PROCESS_ID $TASK_ID /data/$PROCESS_ID deu Fraktur true"
+COMMAND="for_production.sh --proc-id $PROCESS_ID --task-id $TASK_ID --lang deu --script Fraktur"
 WORKFLOW_FILE="ocr-workflow.sh"
 if test -f "/usr/local/kitodo/metadata/$PROCESS_ID/$WORKFLOW_FILE"; then
-    COMMAND+=" /data/$PROCESS_ID/$WORKFLOW_FILE"
+    COMMAND+=" --workflow /data/$PROCESS_ID/$WORKFLOW_FILE"
 fi
+COMMAND+=" /data/$PROCESS_ID"
 
 logger -p user.notice -t $TASK "ssh destination 'ocrd@$OCRD_MANAGER_HOST' port '${OCRD_MANAGER_PORT:-22}' running command '$COMMAND'"
 
```
(this will then have to go into data.zip again)

**Review by markusweigelt — COMMENTED** [review]
This looks very good! I'll then test the changes at least for Production against our stack (with changes from above) and then I'll merge if it works.

In the orcd_lib.sh script I suggest to name functions and values perspectively independent from our applications Kitodo.Production and Kitodo.Presentation and use functional naming. But we could also do this later in a separate issue / PR so that it does not become too much at once.

e.g.
`parse_args_for_presentation` -> `parse_args_for_mets_processing` 
`parse_args_for_production`  -> `parse_args_for_procdir_processing` 

For closing the task in Kitodo.Production I can imagine a seperated lib kitodo-production_lib.sh. This contains all application-specific functions come.

Afterwards the manager supports Kitodo.Production but the core functionality is independent and can be used with any application.

**Comment by markusweigelt** [comment]
Mainly I am concerned about the naming in the script ocrd_lib.sh. I rather saw this lib as a fixed. So the user does not have to make any adjustments here. I think it would be good to keep the applications out of there regarding also the updateability of the ocrd_lib.sh script. So that only adjustments in the scripts which use the library must be made.

**Comment by bertsky** [comment]
I see – agreed! Then lets move the arg parsers from ocrd_lib.sh to the top-level scripts.

**Review by markusweigelt — APPROVED** [review]

**Pull request merged**
